---

###################
# Install OpenVPN
###################

# Inventory: vpn_inventory


# Install OpenVPN
- hosts: ovpn-node
  gather_facts: no
  become: true

  vars:
    # FIXME Replace with actual VPC CIDR
    cidr_vpc: "10.0.0.0/16"
    # FIXME Replace with actual internal DNS Zone name (ignore if internal DNS is not used)
    internal_dns_zone: "leapforward.aws"
    openvpn_clients:
      - leapforward

  pre_tasks:
    - name: Update packages
      raw: sudo apt-get update
      become: true
    - name: Install python
      raw: sudo apt-get -y install python-simplejson
      become: true
    # Wait until SSH responds
    - name: Wait until SSH is available
      local_action: wait_for port=22 host="{{ ansible_ssh_host | default(inventory_hostname) }}" search_regex=OpenSSH
      become: false

  roles:
    - openvpn

  post_tasks:
    # Download zip file containing OpenVPN client configuration
    - name: Fetch client configs
      fetch: src=/etc/openvpn/clients/{{ item }}.zip dest={{ playbook_dir }}/{{ item }}.vpn.zip flat=yes
      with_items: "{{ openvpn_clients }}"
