---
- hosts: kube-nodes
  name: Copying TLS Certs
  remote_user: ubuntu
  vars_files:
    - variables.yaml

  tasks:
    - name: Copying {{PEM_CA}} to {{NODE_BASE_DIR}}
      copy:
        src: "{{CERTS_DIR}}/{{PEM_CA}}"
        dest: "{{NODE_BASE_DIR}}"
    - name: Copying {{PEM_KUBERNETES_KEY}} to {{NODE_BASE_DIR}}
      copy:
        src: "{{CERTS_DIR}}/{{PEM_KUBERNETES_KEY}}"
        dest: "{{NODE_BASE_DIR}}"
    - name: Copying {{PEM_KUBERNETES}} to {{NODE_BASE_DIR}}
      copy:
        src: "{{CERTS_DIR}}/{{PEM_KUBERNETES}}"
        dest: "{{NODE_BASE_DIR}}"
