---
- hosts: kube-controllers
  name: Bootstrapping an H/A etcd cluster
  remote_user: ubuntu
  vars_files:
    - variables.yaml

  tasks:
    - name: "Creating etcd config directory: {{ETCD_CONFIG_DIR}}"
      raw: mkdir -p {{ETCD_CONFIG_DIR}}
      become: true
    - name: "Copying {{PEM_CA}} to {{ETCD_CONFIG_DIR}}"
      copy:
        src: "{{CERTS_DIR}}/{{PEM_CA}}"
        dest: "{{ETCD_CONFIG_DIR}}"
      become: true
    - name: "Copying {{PEM_KUBERNETES_KEY}} to {{ETCD_CONFIG_DIR}}"
      copy:
        src: "{{CERTS_DIR}}/{{PEM_KUBERNETES_KEY}}"
        dest: "{{ETCD_CONFIG_DIR}}"
      become: true
    - name: "Copying {{PEM_KUBERNETES}} to {{ETCD_CONFIG_DIR}}"
      copy:
        src: "{{CERTS_DIR}}/{{PEM_KUBERNETES}}"
        dest: "{{ETCD_CONFIG_DIR}}"
      become: true
    - name: "Downloading {{ETCD_RELEASE_BINARY_NAME}}"
      raw: wget {{ETCD_REPOSITORY}}/{{ETCD_RELEASE_BINARY_NAME}}.tar.gz
    - name: "Extracting {{ETCD_RELEASE_BINARY_NAME}}.tar.gz"
      raw: tar -xvf {{ETCD_RELEASE_BINARY_NAME}}.tar.gz
    - name: "Moving etcd binaries to {{BIN_DIR}}"
      raw: mv {{ETCD_RELEASE_BINARY_NAME}}/etcd* {{BIN_DIR}}
      become: true
    - name: "Cleaning up temporary etcd file and directory"
      raw: rm -rf {{ETCD_RELEASE_BINARY_NAME}}*
    - name: "Creating etcd data directory: {{ETCD_DATA_DIR}}"
      raw: mkdir -p {{ETCD_DATA_DIR}}
      become: true
    - name: "Creating service directory: {{SERVICE_DIR}}"
      raw: mkdir -p {{SERVICE_DIR}}
      become: true
    - name: "Evaluating {{TPL_ETCD_SERVICE}} template and copying it to the service directory"
      become: true
      template:
        src: "{{TEMPLATES_DIR}}/{{TPL_ETCD_SERVICE}}"
        dest: "{{SERVICE_DIR}}/{{ETCD}}.service"
    - name: "Starting etcd"
      become: true
      systemd:
        name: etcd
        daemon_reload: yes
        enabled: True
        state: started
