---
- hosts: kube-nodes
  remote_user: ubuntu
  gather_facts: no

  pre_tasks:
    - name: Update packages
      raw: sudo apt-get update
      become: true
    - name: Install python
      raw: sudo apt-get -y install python-simplejson
      become: true

- include: certs.yaml
- include: etcd.yaml
