NODE_BASE_DIR: "/home/ubuntu/"
BIN_DIR: "/usr/bin/"
SERVICE_DIR: "/etc/systemd/system"

ETCD: "etcd"
ETCD_CONFIG_DIR: "/etc/etcd"
ETCD_DATA_DIR: "/var/lib/etcd"
ETCD_REPOSITORY: "https://github.com/coreos/etcd/releases/download/v3.0.10"
ETCD_RELEASE_BINARY_NAME: "etcd-v3.0.10-linux-amd64"
ETCD_NODES:
  nk-kubernetes-controller-0:
    ip: 10.240.0.10
    name: controller0
  nk-kubernetes-controller-1:
    ip: 10.240.0.11
    name: controller1
  nk-kubernetes-controller-2:
    ip: 10.240.0.12
    name: controller2

KUBERNETES_CONFIG_DIR: "/var/lib/kubernetes"
KUBERNETES_REPOSITORY: "https://storage.googleapis.com/kubernetes-release/release/v1.4.0/bin/linux/amd64"
KUBERNETES_API_SERVER: "kube-apiserver"
KUBERNETES_CONTROLLER_MANAGER: "kube-controller-manager"
KUBERNETES_SCHEDULER: "kube-scheduler"
KUBERNETES_CONTROLLER: "kubectl"
KUBERNETES_AUTHORIZATION_POLICY_LOCATION: "https://raw.githubusercontent.com/kelseyhightower/kubernetes-the-hard-way/master"
KUBERNETES_AUTHORIZATION_POLICY_NAME: "authorization-policy.jsonl"
KUBERNETES_AUTH_TOKEN: "token.csv"

CERTS_DIR: "../certs"
TOKENS_DIR: "../tokens"
TEMPLATES_DIR: "./templates"

CURRENT_NODE: "{{ hostvars[inventory_hostname]['ec2_tag_Name'] }}"

PEM_CA: "ca.pem"
PEM_KUBERNETES: "kubernetes.pem"
PEM_KUBERNETES_KEY: "kubernetes-key.pem"

TPL_ETCD_SERVICE: "etcd.service.j2"
TPL_KUBE_APISERVER_SERVICE: "kube-apiserver.service.j2"
TPL_KUBE_CONTROLLER_MANAGER_SERVICE: "kube-controller-manager.service.j2"
TPL_KUBE_SCHEDULER_SERVICE: "kube-scheduler.service.j2"
