KUBE_NODE_BASE_DIR: "/home/ubuntu/"
ETCD_CONFIG_DIR: "/etc/etcd"
ETCD_DATA_DIR: "/var/lib/etcd"
ETCD_SERVICE_DIR: "/etc/systemd/system"
ETCD_REPOSITORY: "https://github.com/coreos/etcd/releases/download/v3.0.10"
ETCD_RELEASE_BINARY_NAME: "etcd-v3.0.10-linux-amd64"
BIN_DIR: "/usr/bin/"
CERTS_DIR: "../certs"
CURRENT_NODE: "{{ hostvars[inventory_hostname]['ec2_tag_Name'] }}"
ETCD_NODES:
  nk-kubernetes-controller-0:
    ip: 10.240.0.10
    name: controller0
  nk-kubernetes-controller-1:
    ip: 10.240.0.11
    name: controller1
  nk-kubernetes-controller-2:
    ip: 10.240.0.12
    name: controller2
